{{- /* OnePasswordItem resources in release namespace. Requires 1Password operator. */}}
{{- /* itemPath: from vault + item (vault from entry.vault or defaultVault). Full path in item supported for backward compat. */}}
{{- /* secretName: .name defaults to item (when item is full path, use last path segment for the Secret name). */}}
{{- if and (ne .Values.enabled false) (ne (toString (.Values.enabled | default "")) "false") .Values.items }}
{{- range .Values.items }}
{{- if not .item }}
{{- fail (printf "onepassworditem: each entry must have 'item'" ) }}
{{- end }}
{{- $vault := default .vault $.Values.defaultVault }}
{{- $itemPath := .item }}
{{- if not (hasPrefix .item "vaults/") }}
{{- if not $vault }}
{{- fail (printf "onepassworditem: entry with item %q must have 'vault' or chart must set defaultVault when item is not a full path (vaults/.../items/...)" .item) }}
{{- end }}
{{- $itemPath = printf "vaults/%s/items/%s" $vault .item }}
{{- end }}
{{- $secretName := .name | default ( (splitList "/" .item) | last ) }}
{{- $ns := .namespace | default $.Release.Namespace }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secretName }}
  namespace: {{ $ns }}
type: {{ .type | default "Opaque" }}
spec:
  itemPath: {{ $itemPath }}
{{- end }}
{{- end }}
