{{- /* OnePasswordItem resources in release namespace. Requires 1Password operator. */}}
{{- /* itemPath: use .item as-is if it looks like a full path (vaults/.../items/...); else build from vault (item.vault or defaultVault) + item. */}}
{{- if and (ne .Values.enabled false) (ne (toString (.Values.enabled | default "")) "false") .Values.items }}
{{- range .Values.items }}
{{- $vault := default .vault $.Values.defaultVault }}
{{- $itemPath := .item }}
{{- if not (hasPrefix .item "vaults/") }}
{{- $itemPath = printf "vaults/%s/items/%s" (default $vault "") .item }}
{{- end }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
type: {{ .type | default "Opaque" }}
spec:
  itemPath: {{ $itemPath }}
{{- end }}
{{- end }}
